- hosts: haho-work
  become: true

  vars:
    fail2ban_install: False
    add_gpg_key: False
    gpg_key_path: /home/david
    ssh_key_path: /home/david/.ssh
    docker_remove_packages:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
      - runc
    docker_install_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    docker_user: david
    inout_in_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37373438633739663231343834363834356365633830333436643361353031303862643839643331
          3939383632353661353861333235663738643438653564620a363465643632336661366165366238
          36336635643538316533303736316164333238343432623965383463663833623965306265333564
          3336646337303265320a386437623165656566633433333038393139623231353733363962383939
          34303365303064626137303865356132353464393331646364623362303835346162666566356232
          66653065343536373935623537326261356138643664376134303466376266656333363533303432
          303437663238363363616130353233333835

    inout_out_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61343261356263353263366633646136616636666134383432366566646134313164356365313366
          3166653638343330626565373263316666333261656138650a323339653463643339376531633731
          32613563623863313961356536303039373564383336313738356365356136313161633666323163
          6136396561623335380a633838643461333562306363616435356166633530643032353636373936
          33613330333532613064343537626163343738373334336434656636303761396162653633353364
          62313830313633306235653336333632663938626562356432333238343265336161343430386636
          626130323738663031653337313937333265

    basic_packages:
      - git
      - make
      - firewalld
      - pinentry
      - python3-pip

    ansible_pip:
      - ansible-dev-tools
      - ansible-lint
      - ansible-core
  
  tasks:
    - name: place docker-ce.repo
      copy:
        src: repo_files/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
        force: no

    - name: copy over ssh private key
      copy:
        src: ssh_keys/id_rsa
        dest: "{{ ssh_key_path }}/id_rsa"
        owner: david
        group: david
        mode: 0600
        force: no

    - name: copy over ssh public key
      copy:
        src: ssh_keys/id_rsa.pub
        dest: "{{ ssh_key_path }}/id_rsa.pub"
        owner: david
        group: david
        mode: 0600
        force: no

    - name: copy GPG key to homedir
      copy:
        src: gpg_keys/key.gpg
        dest: "{{ gpg_key_path }}/key.gpg"
        owner: david
        group: david
        mode: 0600
        force: no
      when: add_gpg_key == True

    - name: import GPG key
      command: "gpg --import {{ gpg_key_path }}/key.gpg"
      when: add_gpg_key == True

    - name: remove key.gpg
      file:
        path: "{{ gpg_key_path }}/key.gpg"
        state: absent
      when: add_gpg_key == True

    - name: set crontab for work start
      cron:
        name: "work_start"
        day: "1-5"
        minute: "56"
        hour: "7"
        job: "curl {{ inout_in_url }}"
        user: "{{ docker_user }}"

    - name: set crontab for work end
      cron:
        name: "work_end"
        day: "1-5"
        minute: "2"
        hour: "16"
        job: "curl {{ inout_out_url }}"
        user: "{{ docker_user }}"

    - name: install basic packages
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ basic_packages }}"

    - name: enable fail2ban
      service:
        name: fail2ban
        enabled: yes
        state: started
      when: fail2ban_install == True
    
    - name: install firewalld
      package:
        name: firewalld
        state: latest
    
    - name: enable firewalld
      service:
        name: firewalld
        enabled: yes
        state: started
    
    - name: set port to test CNNDOE
      firewalld:
        port: 3838/tcp
        permanent: yes
        state: enabled
    
    - name: reload firewalld
      service:
        name: firewalld
        state: reloaded
  
    - name: remove old docker packages
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ docker_remove_packages }}"
    
    - name: install docker
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ docker_install_packages }}"

    - name: add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
    
    - name: enable docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: copy bash_profile over
      copy:
        src: bash_profiles/haho_work.bash_profile
        dest: /home/david/.bash_profile
        owner: david
        group: david
        mode: 0644
        force: yes

    - name: clone cla-rce-password repo
      ansible.builtin.git:
        repo: git@github.umn.edu:cla-rce/system-passwords.git
        dest: /home/david/system-passwords
        accept_hostkey: no
        key_file: "{{ ssh_key_path }}/id_rsa"
      become: no

    - name: install ansible
      pip:
        name: "{{ ansible_pip }}"
      become: no