---
- hosts: localhost
  gather_facts: false

  vars:
    fedora_version: 35

  tasks:
    - name: upgrade system packages
      yum:
        name: '*'
        state: latest
    
    - name: Get RPM Fusion Free
      get_url:
        url: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
        dest: "/tmp/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"

    - name: Get RPM Fusion non-free
      get_url:
        url: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
        dest: "/tmp/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"

    - name: Install RPM fusion repos
      yum:
        name:
          - "/tmp/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
          - "/tmp/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
        state: present
    
    - name: Add VS Code repo key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Get Zoom client
      get_url:
        url: https://zoom.us/client/latest/zoom_x86_64.rpm
        dest: /tmp/zoom_x86_64.rpm
      
    - name: Get Mullvad client (may not work?)
      get_url:
        url: https://mullvad.net/download/app/rpm/latest/
        dest: /tmp/MullvadVPN.rpm

    - name: Install packages
      yum:
        name:
          - dnf-plugins-core
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
          - steam
          - /tmp/zoom_x86_64.rpm
          - /tmp/MullvadVPN.rpm
          - vlc
          - puppet
        state: present